name: pipeline_plus
description: A Pipeline allows you to pass data through a series of pipes to perform a sequence of operations with the data.
version: 1.1.0
homepage: https://github.com/aydinfatih/pipeline_plus
repository: https://github.com/aydinfatih/pipeline_plus

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
